# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  # rpcURL: spdk json rpc target
  # targetType: nvme-rdma, nvme-tcp, iscsi
  # targetAddr: target service IP
  config.json: |-
    {
      "nodes": [
        {
          "name": "spdk-1",
          "rpcURL": "http://192.168.61.25:829/",
          "targetType": "nvme-tcp",
          "targetAddr": "192.168.61.25"
        }
      ]
    }
