apiVersion: v1
kind: Pod
metadata:
  name: spdk-pod
  labels:
    app: spdk-pod
spec:
  containers:
  - name: spdk-pod
    image: ubuntu
    command: ['sleep','604800']
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/spdkvol"
      name: spdk-volume
    volumeMounts:
    - mountPath: "/F2PT"
      name: f2pt-volume
  volumes:
  - name: spdk-volume
    persistentVolumeClaim:
      claimName: gluesyscsi-pvc
  - name: f2pt-volume
    persistentVolumeClaim:
      claimName: f2pt-pvc
