# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluesyscsi-sc
provisioner: csi.gluesys.io
parameters:
  fsType: xfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
